server:
  port: 4000
minio:
  url: http://localhost:9000
  accessKey: root
  secretKey: Wyj199751
storage:
  service:
    type: minio
logging:
  config: classpath:log4j2-spring.xml

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB