server:
  port: 4000
minio:
  url: http://192.168.134.129:9000
  accessKey: minioadmin
  secretKey: minioadmin
storage:
  service:
    type: minio
nacos:
  config:
    access-key: nacos
    secret-key: nacos
    data-id: jc-club-oss
    group: DEFAULT_GROUP
    type: yaml
    server-addr: http://192.168.134.129:8848/
    auto-refresh: true
    remote-first: true
    bootstrap:
      enable: true