spring:
  datasource:
    username: root
    password: Wyj199751
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jc-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: Wyj199751
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
 # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Wyj199751
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

logging:
  config: classpath:log4j2-spring.xml

server:
  port: 8000

es:
  cluster[0]:
    name: jc-club
    addr[0]: localhost:9200

xxl:
  job:
    admin:
      addresses: http://localhost:8800/xxl-job-admin
    accessToken: Wyj199751
    executor:
      appname: jc-club-subject
#      address: http://192.168.134.1:8800/
#      ip: 192.168.134.1
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

rocketmq:
  name-server: localhost:9876
  producer:
    group: jc-club-group
    send-message-timeout: 10000